name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*"

concurrency: ${{ github.workflow }}

env:
  TERM: linux

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: run-tests
        uses: ./.github/actions/tests
        with:
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  push:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env for branch
        run: |
          echo "TAG=$(echo ${GITHUB_REF#refs/heads/} | sed 's|\/|-|g')" >> $GITHUB_ENV
        if: github.event_name != 'pull_request'  && startsWith(github.ref, 'refs/heads/')
      - name: Set env for tags
        run: |
          echo "TAG=$(echo ${GITHUB_REF#refs/tags/} | sed 's|\/|-|g')" >> $GITHUB_ENV
        if: github.event_name != 'pull_request'  && startsWith(github.ref, 'refs/tags/')
      - name: Set env for Pull Requests
        run: |
          echo "TAG=$(echo ${GITHUB_HEAD_REF#refs/heads/} | sed 's|\/|-|g')" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'
      - name: create latest tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          export TAG=latest
      - name: Publish container
        run: |
          make build
          make publish
